template_path: remote/cfn-cr-sc-tagger.yaml
stack_name: cfn-cr-sc-tagger
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
hooks:
  before_launch:
    - !cmd "curl https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/cfn-cr-sc-tagger/0.0.9/cfn-cr-sc-tagger.yaml --create-dirs -o templates/remote/cfn-cr-sc-tagger.yaml"
